<%@ Page Title="" Language="C#" MasterPageFile="~/SiteCss.Master" AutoEventWireup="true" CodeBehind="OgrenciDersKonular.aspx.cs" Inherits="GaziProje2014.Forms.OgrenciDersKonular" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <div class="contentUst40">
        <table class="tdTablo">
            <tr>
                <td class="tdCellBaslik">Ders Adı :</td>
                <td colspan="4">
                    <telerik:RadComboBox ID="rdcmbOgrenciOnayliDersler" runat="server" Width="500px" OnSelectedIndexChanged="rdcmbOgrenciOnayliDersler_SelectedIndexChanged" AutoPostBack="true">
                    </telerik:RadComboBox>
                </td>
                <td class="tdCellBaslik"></td>                                                                                       
            </tr>
        </table>
    </div>
    <div class="contentUst40Golge">
    </div>


    <div class="contentOrta40x40">    
        
        <telerik:RadTreeList ID="dersIcerikTreeList" runat="server" DataKeyNames="IcerikId" ParentDataKeyNames="IcerikPId" AutoGenerateColumns="False" OnNeedDataSource="dersIcerikTreeList_NeedDataSource" NoRecordsText="Henüz Hiç İçerik Eklenmedi.">
            <Columns>
               <telerik:TreeListSelectColumn HeaderStyle-Width="40px">
               </telerik:TreeListSelectColumn>

              <telerik:TreeListTemplateColumn UniqueName="FileColumn" HeaderText="Name">
                        <HeaderStyle></HeaderStyle>
                        <ItemTemplate>
                            <%--<asp:Image ID="FileType" runat="server" AlternateText="FileType" ImageUrl='<%#(string)Eval("type")=="Folder"?"folder.png":"file.png" %>'></asp:Image>--%>
                            <%--<asp:Image ID="FileType" runat="server" AlternateText="FileType"  ImageUrl="~/Style/Arsiv2.png"></asp:Image>--%>
                            <asp:Image ID="FileType" runat="server" AlternateText="FileType"  ImageUrl='<%#Eval("IconUrl") %>'></asp:Image>
                            <asp:Label ID="Label1" runat="server" Text='<%#Eval("IcerikAdi") %>'></asp:Label>
                        </ItemTemplate>
              </telerik:TreeListTemplateColumn>

              <telerik:TreeListBoundColumn DataField="KayitTarihi" UniqueName="KayitTarihi" HeaderText="KayitTarihi" HeaderStyle-Width="150px" >
              </telerik:TreeListBoundColumn>

              <telerik:TreeListBoundColumn DataField="IcerikId" UniqueName="IcerikId" HeaderText="IcerikId"  HeaderStyle-Width="30px" Visible="false">
              </telerik:TreeListBoundColumn>

              <telerik:TreeListBoundColumn DataField="IcerikPId" UniqueName="IcerikPId" HeaderText="IcerikPId" HeaderStyle-Width="30px" Visible="false">
              </telerik:TreeListBoundColumn>
            </Columns>


            <ClientSettings>
                <Selecting AllowItemSelection="True" />
            </ClientSettings>
            <ExportSettings>
            <Excel PageLeftMargin="0.7in" PageRightMargin="0.7in"></Excel>

            <Pdf PageWidth="8.5in" PageHeight="11in"></Pdf>
            </ExportSettings>

            <EditFormSettings EditFormType="AutoGenerated"></EditFormSettings>

            <ValidationSettings CommandsToValidate="PerformInsert,Update"></ValidationSettings>

            <PagerStyle PageSizeControlType="RadComboBox"></PagerStyle>

        </telerik:RadTreeList>  

    </div>   
         
    <div class="contentAlt30">
        <telerik:RadButton Width="150px" ID="btnDersIcerikGoruntule" runat="server" Text="Konuyu Görüntüle" OnClick="btnDersIcerikGoruntule_Click" ></telerik:RadButton> 
    </div>
    <div class="contentAlt30Golge"> 
    </div>

</asp:Content>
