<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm3.aspx.cs" Inherits="GaziProje2014.EskiFormlar.WebForm3" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
<script type="text/javascript">
    function FireSelectCommand() {
        var treelist = $find("<%= RadTreeList1.ClientID %>");
        treelist.fireCommand("Select", 0);
    }
</script>

    <form id="form1" runat="server">
    <div>
    
        <telerik:RadScriptManager ID="RadScriptManager1" Runat="server">
        </telerik:RadScriptManager>
        <telerik:RadTreeList ID="RadTreeList1" runat="server" DataKeyNames="Id" DataSourceID="SqlDataSource1" ParentDataKeyNames="PId">
            <ClientSettings>
                <Selecting AllowItemSelection="True" />
            </ClientSettings>
<ExportSettings>
<Excel PageLeftMargin="0.7in" PageRightMargin="0.7in"></Excel>

<Pdf PageWidth="8.5in" PageHeight="11in"></Pdf>
</ExportSettings>

<EditFormSettings EditFormType="AutoGenerated"></EditFormSettings>

<ValidationSettings CommandsToValidate="PerformInsert,Update"></ValidationSettings>

<PagerStyle PageSizeControlType="RadComboBox"></PagerStyle>
        </telerik:RadTreeList>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:GAZIConnectionString %>" SelectCommand="SELECT [Id], [PId], [PFormBaslik], [FormBaslik], [FormAdi], [FormAciklama], [FormImageUrl] FROM [Formlar]"></asp:SqlDataSource>
    
    </div>
    </form>
</body>
</html>
