//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersIcerikler
    {
        public int IcerikId { get; set; }
        public Nullable<int> IcerikPId { get; set; }
        public Nullable<int> OgretmenDersId { get; set; }
        public string IcerikAdi { get; set; }
        public Nullable<int> IcerikTip { get; set; }
        public string IcerikText { get; set; }
        public string IcerikUrl { get; set; }
        public Nullable<int> DersSira { get; set; }
        public string IconUrl { get; set; }
        public Nullable<int> EkleyenId { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<bool> GenelIcerik { get; set; }
        public string UrlName { get; set; }
        public string ThumbnailPath { get; set; }
        public Nullable<int> VideoSaniye { get; set; }
        public string UrlAciklama { get; set; }
    }
}
