//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyuruKullanicilar
    {
        public int Id { get; set; }
        public Nullable<int> DuyuruId { get; set; }
        public Nullable<int> KullaniciTipiId { get; set; }
    
        public virtual Duyurular Duyurular { get; set; }
    }
}
