//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formlar
    {
        public int Id { get; set; }
        public Nullable<int> PId { get; set; }
        public string PFormBaslik { get; set; }
        public string FormBaslik { get; set; }
        public string FormAdi { get; set; }
        public string FormAciklama { get; set; }
        public string FormImageUrl { get; set; }
    }
}
