//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAZIEntities : DbContext
    {
        public GAZIEntities()
            : base("name=GAZIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DuyuruKullanicilar> DuyuruKullanicilar { get; set; }
        public virtual DbSet<Duyurular> Duyurular { get; set; }
        public virtual DbSet<HareketTipleri> HareketTipleri { get; set; }
        public virtual DbSet<Il> Il { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<KullaniciFormlar> KullaniciFormlar { get; set; }
        public virtual DbSet<KullaniciLogAna> KullaniciLogAna { get; set; }
        public virtual DbSet<KullaniciLogDetail> KullaniciLogDetail { get; set; }
        public virtual DbSet<KullaniciTipleri> KullaniciTipleri { get; set; }
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<OgretmenDersler> OgretmenDersler { get; set; }
        public virtual DbSet<OgrenciDersler> OgrenciDersler { get; set; }
        public virtual DbSet<Formlar> Formlar { get; set; }
        public virtual DbSet<SinavDetay> SinavDetay { get; set; }
        public virtual DbSet<Sorular> Sorular { get; set; }
        public virtual DbSet<OgrenciSinav> OgrenciSinav { get; set; }
        public virtual DbSet<OgrenciSinavDetay> OgrenciSinavDetay { get; set; }
        public virtual DbSet<Sinav> Sinav { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<DersIcerikler> DersIcerikler { get; set; }
    }
}
