//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilce
    {
        public int IlceKodu { get; set; }
        public string IlceAdi { get; set; }
        public Nullable<int> IlKodu { get; set; }
        public string IlAdi { get; set; }
        public string IegmIlceKodu { get; set; }
        public string IlceSon { get; set; }
    }
}
