//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int KullaniciId { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciSifre { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<int> KullaniciTipi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> Cinsiyet { get; set; }
        public string CepTel { get; set; }
        public string EvTel { get; set; }
        public string Email { get; set; }
        public Nullable<int> IlKodu { get; set; }
        public Nullable<int> IlceKodu { get; set; }
        public string Adres { get; set; }
        public string Resim { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<bool> Onay { get; set; }
        public string DokumanAdres { get; set; }
        public string SkinName { get; set; }
        public string BackGround { get; set; }
    }
}
