//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciTipleri
    {
        public int KullaniciTipId { get; set; }
        public string KullaniciTipAdi { get; set; }
        public string KullaniciTipAciklama { get; set; }
        public Nullable<bool> KullaniciTipDurum { get; set; }
    }
}
