//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciSinav
    {
        public int OgrenciSinavId { get; set; }
        public Nullable<int> SinavId { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public Nullable<System.DateTime> BaslamaZamani { get; set; }
        public Nullable<System.DateTime> BitisZamani { get; set; }
        public string IPNumarasi { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
        public Nullable<int> ToplamOnlineSure { get; set; }
    }
}
