//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgretmenDersler
    {
        public int OgretmenDersId { get; set; }
        public Nullable<int> OgretmenId { get; set; }
        public Nullable<int> DersId { get; set; }
        public Nullable<bool> OgretmenOnayi { get; set; }
        public Nullable<bool> UstOnay { get; set; }
    }
}
