//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciDersler
    {
        public int OgrenciDersId { get; set; }
        public Nullable<int> OgretmenDersId { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public Nullable<bool> OgrenciOnayi { get; set; }
        public Nullable<bool> UstOnay { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> OnayTarihi { get; set; }
    }
}
