//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinav
    {
        public int SinavId { get; set; }
        public Nullable<int> OgretmenDersId { get; set; }
        public string SinavAdi { get; set; }
        public string SinavAciklama { get; set; }
        public Nullable<int> Sure { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<System.DateTime> KayitTrh { get; set; }
        public Nullable<int> EkleyenId { get; set; }
        public Nullable<bool> UstOnay { get; set; }
    }
}
