//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaziProje2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        public int SoruId { get; set; }
        public Nullable<int> OgretmenDersId { get; set; }
        public string SoruIcerik { get; set; }
        public string SoruKonu { get; set; }
        public string SoruResim { get; set; }
        public Nullable<int> CvpSayisi { get; set; }
        public Nullable<int> DogruCvp { get; set; }
        public string Cvp1 { get; set; }
        public string Cvp2 { get; set; }
        public string Cvp3 { get; set; }
        public string Cvp4 { get; set; }
        public string Cvp5 { get; set; }
        public Nullable<int> EkleyenId { get; set; }
        public Nullable<System.DateTime> KayitTrh { get; set; }
    }
}
